Update cron.yml fetch news

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -40,6 +40,10 @@ jobs:
       - name: Run scripts
         continue-on-error: true
         run: |
+
+          echo "Running n500.py..."
+          python fetch_news.py || echo "fetch)news failed"
+          
           echo "Running n500.py..."
           python n500.py || echo "n500 failed"
 
