Update cron.yml

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -80,7 +80,7 @@ jobs:
         run: |
           echo "Running LIGHT mode"
 
-          python -u fetch_news.py || echo "news failed"
+          #python -u fetch_news.py || echo "news failed"
           python build.py || echo "build failed"
 
       # 💾 Commit changes
