Update cron.yml

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -41,8 +41,8 @@ jobs:
         continue-on-error: true
         run: |
 
-          echo "Running n500.py..."
-          python fetch_news.py || echo "fetch)news failed"
+          echo "Running fetch_news.py..."
+          python fetch_news.py || echo "fetch_news failed"
           
           echo "Running n500.py..."
           python n500.py || echo "n500 failed"
